name: deploy-jupyter-book

on:
    push:
        branches:
            - main
            - feat/update_docs_and_details

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
    deploy-book:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # Install dependencies
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  pip install jupyter-book
            # Build the book
            - name: Build the book
              run: |
                  jupyter-book build notebooks
            # Push the book's HTML to github-pages
            - name: GitHub Pages action
              uses: peaceiris/actions-gh-pages@v3.5.9
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: notebooks/_build/html
